import type { BuildingData, Point3D } from '../types/building';

export const DEFAULT_FACADE_PARAMETERS: FacadeParameters = {
  wwr: 0.4,
  windowWidth: 1.2,
  windowHeight: 1.5,
  // Keep row split at zero so frontend and Honeybee use single-row apertures by default.
  windowSpacing: 0,
  wallThickness: 0.3,
  additionalHorizontalShadingDepth: 0,
  additionalVerticalShadingDepth: 0
};

export const MAX_WWR = 0.95;

export interface FacadeParameters {
  wwr: number;
  windowWidth: number;
  windowHeight: number;
  windowSpacing: number;
  wallThickness: number;
  additionalHorizontalShadingDepth: number;
  additionalVerticalShadingDepth: number;
}

export type FacadeShadeKind = 'overhang' | 'left-fin' | 'right-fin';

export interface FacadeShade {
  kind: FacadeShadeKind;
  depth: number;
}

export interface FacadeAperture {
  edgeIndex: number;
  floorNumber: number;
  center: { x: number; y: number; z: number };
  right: { x: number; y: 0; z: number };
  outward: { x: number; y: 0; z: number };
  width: number;
  height: number;
  shades: [FacadeShade, FacadeShade, FacadeShade];
}

export interface FacadeLayoutResult {
  apertures: FacadeAperture[];
  requestedWwr: number;
}

interface SubRectangle {
  centerAlongEdge: number;
  bottom: number;
  width: number;
  height: number;
}

export const clampWwr = (value: number | undefined): number => {
  const resolved = Number.isFinite(value) ? (value as number) : DEFAULT_FACADE_PARAMETERS.wwr;
  return Math.max(0, Math.min(MAX_WWR, resolved));
};

export const getBuildingFacadeParameters = (building: BuildingData): FacadeParameters => ({
  ...DEFAULT_FACADE_PARAMETERS,
  wwr: clampWwr(building.window_to_wall_ratio),
  additionalHorizontalShadingDepth: building.window_overhang
    ? (building.window_overhang_depth ?? 0)
    : 0
});

/** Honeybee expects floor polygons to be counter-clockwise in its XY plane. */
export const ensureHoneybeeCounterClockwise = (points: Point3D[]): Point3D[] => {
  const signedArea = points.reduce((area, point, index) => {
    const next = points[(index + 1) % points.length];
    return area + point.x * next.z - next.x * point.z;
  }, 0) / 2;
  return signedArea >= 0
    ? points.map(point => ({ ...point }))
    : [...points].reverse().map(point => ({ ...point }));
};

/** Match Python's round-to-even behavior used by Ladybug Geometry. */
const pythonRound = (value: number): number => {
  const floor = Math.floor(value);
  const fraction = value - floor;
  if (Math.abs(fraction - 0.5) < Number.EPSILON * Math.max(1, Math.abs(value))) {
    return floor % 2 === 0 ? floor : floor + 1;
  }
  return Math.round(value);
};

/**
 * TypeScript port of Face3D.sub_rects_from_rect_ratio, which is called by
 * Honeybee Face.apertures_by_ratio_rectangle for the rectangular wall faces
 * generated by the daylight backend.
 */
export const buildHoneybeeSubRectangles = (
  parentBase: number,
  parentHeight: number,
  ratio: number,
  requestedHeight: number,
  requestedSillHeight: number,
  horizontalSeparation: number,
  verticalSeparation: number
): SubRectangle[] => {
  const wwr = clampWwr(ratio);
  if (wwr <= 0 || parentBase <= 0 || parentHeight <= 0) {
    return [];
  }

  const targetArea = parentBase * parentHeight * wwr;
  const maxAreaForSubdivision = parentBase * 0.98 * requestedHeight;
  let subRectHeight = Math.min(requestedHeight, parentHeight * 0.98);
  const sillHeight = Math.max(requestedSillHeight, parentHeight * 0.01);

  if (targetArea < maxAreaForSubdivision) {
    const divisionCount = Math.max(
      1,
      parentBase > horizontalSeparation / 2
        ? pythonRound(parentBase / horizontalSeparation)
        : 1
    );
    const segmentWidth = parentBase / divisionCount;
    const windowWidth = (targetArea / subRectHeight) / divisionCount;
    const actualSill = Math.min(sillHeight, parentHeight * 0.99 - subRectHeight);

    let split = verticalSeparation;
    const maxVerticalSplit = parentHeight - sillHeight - subRectHeight - parentHeight * 0.02;
    if (split < 0 || maxVerticalSplit < 0) {
      split = 0;
    } else if (split > maxVerticalSplit) {
      split = maxVerticalSplit;
    }

    const rectangles: SubRectangle[] = [];
    if (split !== 0) {
      subRectHeight /= 2;
    }

    for (let row = 0; row < (split !== 0 ? 2 : 1); row += 1) {
      const bottom = actualSill + row * (subRectHeight + split);
      for (let column = 0; column < divisionCount; column += 1) {
        rectangles.push({
          centerAlongEdge: (column + 0.5) * segmentWidth,
          bottom,
          width: windowWidth,
          height: subRectHeight
        });
      }
    }
    return rectangles;
  }

  const windowWidth = parentBase * 0.98;
  let totalWindowHeight = targetArea / windowWidth;
  const actualSill = Math.min(sillHeight, parentHeight * 0.99 - totalWindowHeight);
  let split = verticalSeparation;
  const maxVerticalSplit = parentHeight - sillHeight - totalWindowHeight - parentHeight * 0.02;
  if (split < 0 || maxVerticalSplit < 0) {
    split = 0;
  } else if (split > maxVerticalSplit) {
    split = maxVerticalSplit;
  }

  if (split === 0) {
    return [{
      centerAlongEdge: parentBase / 2,
      bottom: actualSill,
      width: windowWidth,
      height: totalWindowHeight
    }];
  }

  totalWindowHeight /= 2;
  return [0, 1].map((row) => ({
    centerAlongEdge: parentBase / 2,
    bottom: actualSill + row * (totalWindowHeight + split),
    width: windowWidth,
    height: totalWindowHeight
  }));
};

export const buildFacadeLayout = (
  footprint: Point3D[],
  floors: number,
  floorHeight: number,
  parameters: FacadeParameters
): FacadeLayoutResult => {
  const orderedFootprint = ensureHoneybeeCounterClockwise(footprint);
  const requestedWwr = clampWwr(parameters.wwr);
  const apertures: FacadeAperture[] = [];
  const horizontalShadeDepth = parameters.wallThickness + parameters.additionalHorizontalShadingDepth;
  const verticalShadeDepth = parameters.wallThickness + parameters.additionalVerticalShadingDepth;
  const sillHeight = Math.max(0, (floorHeight - parameters.windowHeight) / 2);
  const centerlineSeparation = Math.max(parameters.windowWidth + parameters.windowSpacing, 0.01);

  for (let floorIndex = 0; floorIndex < Math.max(1, floors); floorIndex += 1) {
    for (let edgeIndex = 0; edgeIndex < orderedFootprint.length; edgeIndex += 1) {
      const start = orderedFootprint[edgeIndex];
      const end = orderedFootprint[(edgeIndex + 1) % orderedFootprint.length];
      const deltaX = end.x - start.x;
      const deltaZ = end.z - start.z;
      const edgeLength = Math.hypot(deltaX, deltaZ);
      if (edgeLength <= 1e-9) {
        continue;
      }

      const right = { x: deltaX / edgeLength, y: 0 as const, z: deltaZ / edgeLength };
      // Footprints are normalized counter-clockwise; the right-hand side of
      // each directed edge is therefore the exterior of the room.
      const outward = { x: right.z, y: 0 as const, z: -right.x };
      const subRectangles = buildHoneybeeSubRectangles(
        edgeLength,
        floorHeight,
        requestedWwr,
        parameters.windowHeight,
        sillHeight,
        centerlineSeparation,
        parameters.windowSpacing
      );

      for (const rectangle of subRectangles) {
        apertures.push({
          edgeIndex,
          floorNumber: floorIndex + 1,
          center: {
            x: start.x + right.x * rectangle.centerAlongEdge,
            y: floorIndex * floorHeight + rectangle.bottom + rectangle.height / 2,
            z: start.z + right.z * rectangle.centerAlongEdge
          },
          right,
          outward,
          width: rectangle.width,
          height: rectangle.height,
          shades: [
            { kind: 'overhang', depth: horizontalShadeDepth },
            { kind: 'left-fin', depth: verticalShadeDepth },
            { kind: 'right-fin', depth: verticalShadeDepth }
          ]
        });
      }
    }
  }

  return { apertures, requestedWwr };
};
